language: python
python:
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE=project.settings PYTHONPATH=`pwd`/src
install:
  - "pip install --allow-all-external  --allow-unverified django-holodeck -e ."
script:
  - django-admin.py test app
