language: python
python:
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE=project.settings PYTHONPATH=`pwd`/src
before_install:
  - mkdir -p src/project/media/uploads
install:
  - "pip install -r requirements.txt"
  - "python setup.py develop"
script:
  - django-admin.py test app
